import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavContainer from "@/Components/Home/Navbar/NavContainer";
import Footer from "@/Components/Home/Footer/Footer";

const font = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${font.className} antialiased bg-gray-800`}
    >
      <body className="min-h-full flex flex-col">
        <NavContainer/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
